import {
  auth,
  catalog,
  create,
  mainRoute,
  reporting,
  updateRouteId,
} from "../static/endPoints";

export const routes = {
  main: mainRoute.MAIN,
  register: auth.REGISTER,
  login: auth.LOGIN,
  logout: auth.LOGOUT,
  dashboard: auth.DASHBOARD,
  catalogFarm: catalog.FARM,
  catalogField: catalog.FIELD,
  catalogMachinery: catalog.MACHINERY,
  catalogFieldCultivation: catalog.FIELD_CULTIVATION,
  createFarm: create.FARM,
  createField: create.FIELD,
  createMachinery: create.MACHINERY,
  createFieldCultivation: create.FIELD_CULTIVATION,
  updateFarm: updateRouteId.FARM,
  updateField: updateRouteId.FIELD,
  updateMachinery: updateRouteId.MACHINERY,
  updateFieldCultivation: updateRouteId.FIELD_CULTIVATION,
  reportingMostMachineries: reporting.MOST_MACHINERIES,
  reportingFieldCropsFarms: reporting.FIELD_BY_CROPS_AND_FARMS,
  reportingMostCommonSoil: reporting.MOST_COMMON_SOIL,
  notFound: mainRoute.NOT_FOUND,
};
