export const mainColors = {
  primaryColor: "#F5CB5C",
  hoverColor: "#E4B126",
  textColor: "#33533",
  hoverTextColor: "#FFFAFA",
  backgroundColorPage: "#E8EDDF",
  updateButtonColor: "#32CD32",
  updateButtonHoverColor: "#008000",
  softDeleteButtonColor: "#FF6347",
  softDeleteButtonHoverColor: "#B22222",
  permDeleteButtonColor: "#FF0000",
  permDeleteButtonHoverColor: "#8B0000",
  textColorButton: "#E8EDDF",
  popupBackgroundColor: "#CFDBD5",
  popupBorderColor: "#333533",
};
